specVersion: 0.2.0
name: early-adopters-subql
version: 0.1.0
description: SubQuery project for querying Early Adopter program participants
repository: "https://github.com/subquery/acala-subql-starter"
schema:
  file: ./schema.graphql
network:
  endpoint: "wss://acala-polkadot.api.onfinality.io/public-ws"
  genesisHash: "0xfc41b9bd8ef8fe53d58c7ea67c794c7ec9a73daf05e6d54b14ff6342c99ba64c"
  dictionary: "https://api.subquery.network/sq/subquery/acala-dictionary"
  chaintypes:
    file: ./dist/chaintypes.js
dataSources:
  - kind: substrate/Runtime
    # Start of program
    startBlock: 327363
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleDexCall
          kind: substrate/CallHandler
          filter:
            module: dex
            success: true
        - handler: handlePositionUpdateEvent
          kind: substrate/EventHandler
          filter:
            module: loans
            method: PositionUpdated
        - handler: handleDotBridgeEvent
          kind: substrate/EventHandler
          filter:
            module: currencies
            method: Transferred
